import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-gray-900`}
      >
        <header className="border-b bg-white/80 backdrop-blur supports-[backdrop-filter]:bg-white/60">
          <div className="mx-auto flex max-w-5xl items-center justify-between px-4 py-3">
            <Link href="/" className="text-lg font-semibold">
              KENT BRYAN V. ASILO EXAM
            </Link>
          </div>
        </header>
        <main className="min-h-[calc(100dvh-56px)] bg-gray-50/60">
          {children}
        </main>
        <footer className="border-t bg-white/80">
          <div className="mx-auto max-w-5xl px-4 py-4 text-center text-xs text-gray-500">
            © {new Date().getFullYear()} EXAM
          </div>
        </footer>
      </body>
    </html>
  );
}
